### ISSUE TITLE
Board size is to large 

### ISSUE THREAD

**Issue by anders-eriksson** [johnvoysey/trello-dashboard#8]
First a big Thank You for this extension! This is what I have missed in Trello.

I have a lot of boards, working as a consultant and each customer has its own board. The dashboard is very nice, but the 'images' of the boards are to large and I can only get 3 of the per row.

It would be nice if I could change the size of the boards so that I get 'at least' 6 of them per row.

I'm running trello-dashboard on my own server, but I'm not a web developer. If you would give me an idea on how to change the size I would appreciate it! Or even better if you could add a configuration...

My monitor is 1920x1200

// Anders
PS! I have updated dashboard.css with the @media (min-width: 1440px) patch.

**Comment by johnvoysey** [comment]
Hi,
Sorry for the delay. I've updated the page to show up to 6 columns on a 1920x1200 screen. If it's still not quite right, adjust the column widths in this section of dashboard.css:
```
@media (min-width: 1920px) {
  .container {
    width: 100%;
    padding: 0 50px;
  }
  /* Show more columns on larger screens */
  .row {
    -moz-column-width: 20em;
    -webkit-column-width: 20em;
  }
```
}
Hope that helps.
